# Generated by Django 5.0.4 on 2024-04-05 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phonebook_app', '0002_alter_person_options_alter_phonenumber_options_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='phonenumber',
            constraint=models.UniqueConstraint(fields=('person', 'is_primary'), name='unique_primary_phone_number'),
        ),
    ]
