# Generated by Django 5.0 on 2024-01-19 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('olx_copy', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='avatar',
        ),
    ]
