# Generated by Django 5.0 on 2024-01-18 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('olx_copy', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='author_slug',
        ),
    ]
