# Generated by Django 5.0 on 2024-01-21 17:31

import olx_copy.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olx_copy', '0002_alter_userprofile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=olx_copy.models.user_avatar_path),
        ),
    ]
