# Generated by Django 5.0.1 on 2024-01-28 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olx_copy', '0002_remove_order_cart_items_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cart_items',
            field=models.ManyToManyField(to='olx_copy.cart', verbose_name='Элементы корзины'),
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
