# Generated by Django 5.0.1 on 2024-01-25 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('olx_copy', '0002_alter_message_options_alter_review_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name': 'Корзина', 'verbose_name_plural': 'Корзины'},
        ),
    ]
