# Generated by Django 5.0 on 2024-01-19 17:09

import olx_copy.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olx_copy', '0002_remove_userprofile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, default='png/user.png', null=True, upload_to=olx_copy.models.user_avatar_path),
        ),
    ]
