# Generated by Django 5.0 on 2024-01-18 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olx_copy', '0003_alter_item_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='messages', to='olx_copy.room', verbose_name='Комната'),
        ),
    ]
