# Generated by Django 5.0 on 2024-01-10 16:29

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olx_copy', '0004_item_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField(default=5, verbose_name='Приоритет')),
                ('expired', models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата и время истечения')),
                ('article', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='olx_copy.item', verbose_name='Объявление')),
            ],
            options={
                'verbose_name': 'Vip объявление',
                'verbose_name_plural': 'Vip объявления',
                'ordering': ('priority', '-expired'),
            },
        ),
    ]
