# Generated by Django 5.0 on 2024-01-20 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olx_copy', '0004_room_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(default='', verbose_name='Текст сообщения'),
        ),
    ]
