# Generated by Django 5.0.1 on 2024-01-25 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('olx_copy', '0006_order_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='item',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
