# Generated by Django 5.0 on 2024-01-11 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olx_copy', '0006_alter_item_options_alter_item_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='discounted_price',
            field=models.PositiveIntegerField(blank=True, help_text='Цена со скидкой, если применена', null=True, verbose_name='Скидочная цена'),
        ),
        migrations.AlterField(
            model_name='itemrating',
            name='is_like',
            field=models.BooleanField(default=True, verbose_name='Понравилось'),
        ),
    ]
