# Generated by Django 5.0 on 2024-01-11 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olx_copy', '0007_item_discounted_price_alter_itemrating_is_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='discount_percentage',
            field=models.FloatField(blank=True, editable=False, null=True, verbose_name='Процент скидки'),
        ),
    ]
