# Generated by Django 5.0 on 2024-01-17 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('olx_copy', '0007_review_user_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='user_profile',
        ),
    ]
