# Generated by Django 5.0 on 2024-01-18 06:01

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olx_copy', '0008_remove_review_user_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, db_index=True, default='', max_length=255, verbose_name='Наименование')),
                ('slug', models.SlugField(blank=True, default='', max_length=300, unique=True, verbose_name='Ссылка')),
                ('token', models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True, verbose_name='Токен')),
            ],
            options={
                'ordering': ('-slug', '-name'),
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, default='', verbose_name='Текст сообщения')),
                ('date_added', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='дата и время добавления')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='messages', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='messages', to='olx_copy.room', verbose_name='Комната')),
            ],
            options={
                'ordering': ('-date_added', '-room'),
            },
        ),
    ]
