# Generated by Django 5.0 on 2024-01-18 07:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olx_copy', '0009_room_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='token',
            field=models.CharField(blank=True, db_index=True, default=uuid.uuid4, max_length=255, null=True, unique=True, verbose_name='Токен'),
        ),
    ]
