# Generated by Django 5.0.1 on 2024-01-15 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wine',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_app.winecategory'),
        ),
        migrations.AlterField(
            model_name='wine',
            name='picture',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='wine_images/'),
        ),
        migrations.AlterField(
            model_name='wine',
            name='qr_code',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='qr_codes/'),
        ),
    ]
