# Generated by Django 5.0.1 on 2024-01-15 14:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0002_alter_wine_category_alter_wine_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wine',
            name='picture',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='wine_images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])]),
        ),
        migrations.AlterField(
            model_name='wine',
            name='qr_code',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='qr_codes/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png'])]),
        ),
    ]
