# Generated by Django 5.0.4 on 2024-04-22 16:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PostRaiting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_like', models.BooleanField(default=True, help_text='Статус понравился ли пользователю товар', verbose_name='Лайк')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_app.post', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Рейтинг Поста',
                'verbose_name_plural': 'Рейтинги Постов',
                'ordering': ('-post', '-author'),
            },
        ),
    ]
