# Generated by Django 5.0.4 on 2024-04-22 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0002_postraiting'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_visible',
            field=models.BooleanField(default=True, verbose_name='Видимость'),
        ),
    ]
