# Generated by Django 5.0.4 on 2024-04-22 16:49

import django_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0003_comment_is_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=django_app.models.user_avatar_path, verbose_name='Аватар'),
        ),
    ]
