# Generated by Django 5.0.4 on 2024-04-23 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0005_post_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-post', '-author', '-created_at', 'is_visible'), 'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментарии'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-title', '-author', '-created_at', 'is_active'), 'verbose_name': 'Пост', 'verbose_name_plural': 'Посты'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ('user__username', '-is_banned'), 'verbose_name': 'Профиль', 'verbose_name_plural': 'Профили'},
        ),
    ]
