# Generated by Django 5.0 on 2023-12-23 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='visible_to_staff',
            field=models.BooleanField(default=True),
        ),
    ]
