# Generated by Django 5.0 on 2023-12-26 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0004_review_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField()),
                ('date_of_receipt', models.DateTimeField()),
                ('date_of_dispatch', models.DateTimeField(blank=True, null=True)),
                ('price', models.FloatField()),
                ('recipient_first_name', models.CharField(max_length=50)),
                ('recipient_last_name', models.CharField(max_length=50)),
                ('recipient_phone_number', models.CharField(max_length=20)),
                ('recipient_address', models.CharField(max_length=255)),
                ('sender_first_name', models.CharField(max_length=50)),
                ('sender_last_name', models.CharField(max_length=50)),
            ],
        ),
    ]
