# Generated by Django 5.0.3 on 2024-04-04 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('slug', models.SlugField(unique=True, verbose_name='Слаг (ссылка латиницей)')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(db_index=True, max_length=100, verbose_name='Фамилия')),
                ('patronymic', models.CharField(blank=True, max_length=100, verbose_name='Отчество')),
                ('tabel_num', models.CharField(db_index=True, max_length=24, unique=True, verbose_name='Табельный номер')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
        migrations.CreateModel(
            name='Clothes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('wearing_period', models.IntegerField(default=0, verbose_name='Период ношения в днях')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clothes_app.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Предмет одежды',
                'verbose_name_plural': 'Предметы одежды',
            },
        ),
        migrations.CreateModel(
            name='ClothesUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_started_wearing', models.DateField(verbose_name='Дата начала ношения')),
                ('date_ended_wearing', models.DateField(blank=True, null=True, verbose_name='Дата окончания ношения')),
                ('clothes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clothes_app.clothes', verbose_name='Предмет одежды')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clothes_app.person', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Экипировка пльзователя',
                'verbose_name_plural': 'Экипировки пользователей',
            },
        ),
    ]
